# action.yml
name: 'Issue RSS Feed'
author: 'lbonanomi'
description: 'Generate an RSS of Github issues by label'
inputs:
  orgs:
    description: 'Organizations to search'
    required: false
    default: 'github,octokit,ubuntu'
  languages:
    description: 'Languages to filter repos against'
    required: false
    default: 'shell,python,go'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.orgs }}
    - ${{ inputs.languages }}
branding:
  icon: 'box'  
  color: 'purple'
