name: RSS

#on:
#  push:
#    branches: [ gh-pages ]

on:
  schedule:
    - cron: "10 * * * *"

jobs:
  concentrator:
    runs-on: ubuntu-latest
    name: Concentrate Help Wanted issues
    
    env:
      TOKEN: ${{ secrets.TOKEN }}  
      
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get issues
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          orgs: 'Github,octokit,ubuntu'
          languages: shell,perl,python,go
