name: RSS

#on:
#  workflow_dispatch:

on:
  workflow_dispatch
  #schedule:
  #  - cron: "00 */6 * * *"

jobs:
  concentrator:
    runs-on: ubuntu-latest
    name: Concentrate Help Wanted issues
    
    env:
      TOKEN: ${{ secrets.TOKEN }}  
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get issues
        uses: ./ # Uses an action in the root directory
        id: RSS
        with:
          #orgs: 'github,cli,octokit,mozilla,autodesk'
          orgs: 'github,octokit'
          languages: shell,perl,python,awk,go
